export const drivers = [
  {
    Id: 1,
    name: "Ali Elchab",
    email: "alielchab01@gmail.com",
    location: "Beirut,Lebanon,Haret Hreik",
    car: "Toyota",
    color: "grey",
    plateNumber: "6F8E24",
  },
  {
    Id: 2,
    name: "Ali Elchab",
    email: "alielchab01@gmail.com",
    location: "Beirut,Lebanon,Haret Hreik",
    car: "Toyota",
    color: "grey",
    plateNumber: "6F8E24",
  },
  {
    Id: 3,
    name: "Ali Elchab",
    email: "alielchab01@gmail.com",
    location: "Beirut,Lebanon,Haret Hreik",
    car: "Toyota",
    color: "grey",
    plateNumber: "6F8E24",
  },
  {
    Id: 4,
    name: "Ali Elchab",
    email: "alielchab01@gmail.com",
    location: "Beirut,Lebanon,Haret Hreik",
    car: "Toyota",
    color: "grey",
    plateNumber: "6F8E24",
  },
];
