export const drivers = [
  {
    id: 1,
    name: "Ali Elchab",
    email: "alielchab01@gmail.com",
    location: "Beirut,Lebanon,Haret Hreik",
    car: "Toyota",
    color: "grey",
    plateNumber: "6F8E24",
  },
  {
    id: 2,
    name: "Ali Elchab",
    email: "alielchab01@gmail.com",
    location: "Beirut,Lebanon,Haret Hreik",
    car: "Toyota",
    color: "grey",
    plateNumber: "6F8E24",
  },
  {
    id: 3,
    name: "Ali Elchab",
    email: "alielchab01@gmail.com",
    location: "Beirut,Lebanon,Haret Hreik",
    car: "Toyota",
    color: "grey",
    plateNumber: "6F8E24",
  },
  {
    id: 6,
    name: "Ali Elchab",
    email: "alielchab01@gmail.com",
    location: "Beirut,Lebanon,Haret Hreik",
    car: "Toyota",
    color: "grey",
    plateNumber: "6F8E24",
  },
];
